name: frontend-presets CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  release:
    uses: MegafonWebLab/github-workflows/.github/workflows/npm-package.yaml@v1.0.1-npm-package
    with:
      enable-typecheck: false
      enable-lint: false
      enable-test: false
      enable-build: false
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
